config/routes.rb
Rails.application.routes.draw do
  resources :jobs

  devise_for :users
  resources :users
  get 'dashboard/index'

  get 'contact' => 'static#contact'

  root 'jobs#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :select_layout

  before_action :authenticate_user!

  private

  def select_layout
  	if devise_controller?
  		'devise'
  	elsif (params[:controller] == 'jobs' and params[:action] == 'index') or
      (params[:controller] == 'jobs' and params[:action] == 'show')
  		'search'
    elsif params[:controller] == 'static'
      'search'
  	else
  		'application'
  	end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  respond_to :html

  def index
    @jobs = Job.order('updated_at DESC')
    respond_with(@jobs)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  skip_before_filter :authenticate_user! , :only => [:index, :show]

  before_filter :set_title

  respond_to :html

  def index
    @jobs = Job.order('updated_at DESC')
    # respond_with(@jobs)
    respond_to do |format|
      format.html
      format.json { render :json => @jobs}
    end
  end

  def show
    set_title(@job.title)
    respond_with(@job)
  end

  def new
    @job = Job.new
    respond_with(@job)
  end

  def edit
  end

  def create
    @job = Job.new(job_params)
    @job.save
    respond_with(@job)
  end

  def update
    @job.update(job_params)
    respond_with(@job)
  end

  def destroy
    @job.destroy
    respond_with(@job)
  end

  private
    def set_job
      @job = Job.find(params[:id])
    end

    def job_params
      params.require(:job).permit(:title, :salary, :department, :link)
    end

    def set_title(page_title = 'Jobs in Laredo Texas')
      @page_title = page_title
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  skip_before_filter :authenticate_user! , :only => [:contact]

  before_filter :set_title

  def contact
    set_title('Post a job')
  end

  private

  def set_title(page_title = 'Jobs in Laredo Texas')
    @page_title = page_title
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:user).permit(:id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Department</th>
      <th>Updated</th>
      <th>Created</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td>
          <strong><%= job.origin %></strong>
          <%= link_to job.title, job.link %>
        </td>
        <td><%= job.department %></td>
        <td><%= job.updated_at.strftime('%b %d @ %I:%M %P') %></td>
        <td>Added <%= time_ago_in_words(job.created_at) %> ago on <%= job.created_at.strftime('%b %d @ %I:%M %P') %></td>
        <td><%= link_to 'Show', job %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :salary %><br>
    <%= f.text_field :salary %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<div ng-controller="SearchCtrl">

  <header 
    class="page-header" 
    style="
      background-image: url('wood_pattern.png'); 
      padding:60px 0;
      margin:0;">
    <div class="container">
      <div 
        class="well col-md-6 col-md-offset-3"
        style="
          background:rgba(255,255,255,0.70);
          border:0;
          margin-bottom:0;">
        <h1 class="text-uppercase" style="font-size:28px;margin-top:0;">Search for jobs</h1>
        <form role="form">
          <input 
            type="search" 
            class="form-control" 
            placeholder="Job title..." 
            ng-model="query"
            style="font-size:24px;height:56px;padding:10px 20px;">
        </form>
      </div><!-- /.well -->
    </div>
  </header>

  <!--
  <div class="btn-group" role="group">
    <button 
      type="button" 
      class="btn btn-default"
      ng-click="setCurrentOrigin(null)">
      All
    </button>
    <button 
      ng-repeat="origin in origins"
      type="button" 
      class="btn btn-default" 
      ng-repeat="origin in origins" 
      ng-click="setCurrentOrigin(origin)" 
      ng-class="{'active':isCurrentOrigin(origin)}">
      {{origin.name}}
    </button>
  </div>
  -->

<div class="container" style="margin-top:10px;">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">

      <div class="panel panel-primary">
        <div class="panel-heading">
          <p ng-if="query">
            Number of jobs currently displayed by your search: <u>{{filteredJobs.length}}</u>.
          </p>

          <p>
            Total jobs listed: {{jobs.length}}.
          </p>
        </div>
        <div class="panel-body" ng-if="filteredJobs.length < 1">
          <h2 class="text-center" >
            No jobs meet your search criteria.
          </h2>
        </div>

        <table class="table table-striped table-hover" ng-show="filteredJobs.length >= 1">
          <thead>
            <tr>
              <th>
                <a href="" ng-click="predicate = 'title'; setReverse()">
                  Title 
                  <span 
                      class="glyphicon glyphicon-arrow-up" 
                      ng-if="!reverse && predicate == 'title'">
                  </span>
                  <span 
                      class="glyphicon glyphicon-arrow-down" 
                      ng-if="reverse && predicate == 'title'">
                  </span>
                </a>
              </th>
              <th>
                <a href="" ng-click="predicate = 'created_at'; setReverse()">
                  Added
                  <span 
                      class="glyphicon glyphicon-arrow-up" 
                      ng-if="!reverse && predicate == 'created_at'">
                  </span>
                  <span 
                      class="glyphicon glyphicon-arrow-down" 
                      ng-if="reverse && predicate == 'created_at'">
                  </span>
                </a>
              </th>
            </tr>
          </thead>
          <tbody>
            <tr ng-repeat="job in 
              (filteredJobs = 
                  ( jobs | 
                  filter:query |
                  orderBy:predicate:reverse )
              )">
              <td>
                <span
                  class="label label-danger"
                  ng-if="todayFormatted == (job.created_at | date:'MMM dd yy')">NEW</span>
                <a href="/jobs/{{job.id}}">{{job.title}}</a>
                <span class="text-muted">{{job.origin}}</span>
              </td>
              <td>{{job.created_at | date:'MMM dd'}}</td>
            </tr>
          </tbody>
        </table>
        </div><!-- /.panel -->
      </div>
    </div><!-- /.row -->
  </div><!-- /.container -->
</div><!-- /.SearchCtrl -->

<br>

<!--
<%= link_to 'New Job', new_job_path %>
-->

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<div class="container" style="margin-top:10px;">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">

<%= link_to '&#8592; Back to all jobs'.html_safe, jobs_path %>

<p id="notice"><%= notice %></p>

<h1>
  <%= @job.title %>
</h1>

<small>
  <span class="text-muted">
    Added <%= time_ago_in_words(@job.created_at) %> ago;
    <%= @job.created_at.strftime('%b %d %Y @ %I:%M%P') %>
  </span>
</small>

<!--
<p>
  <%= link_to 'Edit', edit_job_path(@job) %>
</p>
-->

<dl class="dl-horizontal" style="margin:25px 0;">

  <dt>Organization:</dt>
  <dd><%= @job.origin %></dd>

  <dt>Location:</dt>
  <dd><%= @job.city %>, Texas</dd>

  <dt>Department:</dt>
  <dd><%= @job.department %><dd>

  <% if @job.salary.present? %>
    <dt>Salary:</dt>
    <dd><%= @job.salary %></dd>
  <% end %>

</dl>

<p>
  <%= link_to 'Learn more or apply', @job.link, class: 'btn btn-primary' %>
</p>

<small>
  Last checked for updates:
  <%= time_ago_in_words(@job.updated_at) %> ago
    <%= @job.updated_at.strftime('%b %d %Y @ %I:%M%P') %>
</small>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" ng-app="SearcherApp">
<head>
  <title><%= @page_title %> | Wurkies</title>
  <%= 
    # stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
    stylesheet_link_tag    'application', media: 'all' 
  %>
  <%= 
    # javascript_include_tag 'application', 'data-turbolinks-track' => true 
    javascript_include_tag 'application'
  %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>

    <!-- <div class="navbar navbar-fixed-top"> -->
    <div class="navbar" style="border: 1px solid #e7e7e7;">
      <div class="container">
        <div class="navbar-header">
          <a href="../" class="navbar-brand">Wurkies</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
            <li>
              <%= link_to 'Dashboard', dashboard_index_url %>
            </li>
            <% end %>
            <li>
              <%= link_to 'Jobs', jobs_url %>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "My Profile (#{current_user.email})", current_user %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
          
          <%= "<p class=\"notice\">#{notice}</p>".html_safe if notice %>
          <%= "<p class=\"alert\">#{alert}</p>".html_safe if alert %>

          <%= yield %>
        </div>
      </div>
    </div><!-- /.container -->

    <footer class="footer-sticky" style="margin:0;">
      <div class="container">
        <ul class="list-unstyled" style="margin:20px 0;">
          <% if user_signed_in? %>
            <li><%= link_to 'Dashboard', dashboard_index_url %></li>
          <% end %>
          <li><%= link_to 'Jobs', jobs_url %></li>
          <li><%= link_to 'Contact', contact_url %></li>
        </ul>
      </div>
    </footer>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Wurkies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>    

    <div class="container">
      <%= "<p class='alert alert-info'>#{notice}</p>".html_safe if notice %>
      <%= "<p class='alert alert-warning'>#{alert}</p>".html_safe if alert %>

      <%= yield %>

    </div><!-- /.container -->

    <!--
    <footer class="footer-sticky" style="margin:0;">
      <div class="container">
        <p class="text-center" style="margin:20px 0;">Don't have an account? <a href="#">Sign up today</a>.</p>
      </div>
    </footer>
    -->

</body>
</html>

app/views/layouts/search.html.erb
<!DOCTYPE html>
<html lang="en" ng-app="SearcherApp">
<head>
  <title><%= @page_title %> | Wurkies</title>
  <%= 
    # stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
    stylesheet_link_tag    'application', media: 'all' 
  %>
  <%= 
    # javascript_include_tag 'application', 'data-turbolinks-track' => true 
    javascript_include_tag 'application'
  %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar" style="border: 1px solid #e7e7e7;">
    <div class="container">
      <div class="navbar-header">
        <a href="../" class="navbar-brand">Wurkies</a>
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse" id="navbar-main">

        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to 'Post a job: $100 for 30 days', contact_url %>
          </li>
          <% if user_signed_in? %>
            <li>
              <%= link_to 'Dashboard', dashboard_index_url %>
            </li>
            <li><%= link_to "My Profile (#{current_user.email})", current_user %></li>
            <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          <% end %>
        </ul>

      </div>
    </div>
  </div>
    

  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12">
        
        <%= "<div class=\"alert alert-info\" role=\"alert\">#{notice}</div>".html_safe if notice %>
        <%= "<div class=\"alert alert-warning\" role=\"alert\">#{alert}</p>".html_safe if alert %>

        <!--
        <p class="lead"><strong>Wurkies</strong> is probably the best place to find and list jobs postings in Laredo, Texas. Follow us on Twitter <a href="#" target="_blank">@wurkies</a>, <a href="#" target="_blank">Facebook</a> and <a href="#" target="_blank">Google+</a>.</p>
        -->

        <p class="lead"><strong>Wurkies</strong> is probably the best place to find and list jobs postings in Laredo, Texas. Follow us on Twitter <a href="https://twitter.com/wurkies" target="_blank">@wurkies</a> and <a href="https://www.facebook.com/wurkies" target="_blank">Facebook</a>. Improvements and new features are posted in our <a href="http://wurkies.tumblr.com/" target="_blank">Tumblr blog</a>.</p>

      </div>
    </div>
  </div><!-- /.container -->

  <%= yield %>

  <footer class="footer-sticky" style="margin:0;">
    <div class="container">
      <ul class="list-unstyled" style="margin:20px 0;">
        <% if user_signed_in? %>
          <li><%= link_to 'Dashboard', dashboard_index_url %></li>
        <% end %>
        <li><%= link_to 'Jobs', jobs_url %></li>
        <li><%= link_to 'Contact', contact_url %></li>
      </ul>
    </div>
  </footer>

</body>
</html>

app/views/users/show.html.erb
<h1>My Profile</h1>

<h2><%= @user.email %> <small>ID: <%= @user.id %></small></h2>